### ISSUE TITLE
Full pipeline tutorial

### ISSUE THREAD

**Issue by siamakz** [mpc-msri/EzPC#103]
Thank you very much for this amazing work! I was wondering whether there is any tutorial on using the tools here in an end-to-end fashion. For example, if I have a pre-trained Tensorflow model, how should I create a secure 2-party system based on it using your toolset?

Thanks in advance for your time!

**Comment by bhatuzdaname** [comment]
For now you can read https://github.com/mpc-msri/EzPC/tree/master/Athos#compiling-and-running-models-in-networks-directory-automatically and https://github.com/mpc-msri/EzPC/tree/master/Athos#compiling-your-own-tensorflow-model
The first link describes how to run networks in the Athos/Networks directory but gives some background information that will be required for you. To compile your own model, follow the instructions in the second link. You can pass SCI as the target for 2PC compilation.

I'm actively working on a new end-to-end tutorial and it should be done in a couple of days, so if you prefer to wait you could. I'll close the issue when its done. Thank you.

**Comment by siamakz** [comment]
Thank you very much @bhatuzdaname. I look forward to read the end-to-end tutorial.

**Comment by bhatuzdaname** [comment]
You can see it here. https://pratik-bhatu.medium.com/privacy-preserving-machine-learning-for-healthcare-using-cryptflow-cc6c379fbab7

**Comment by siamakz** [comment]
Thank you @bhatuzdaname
