### ISSUE TITLE
Trouble with compiling SCI library 

### ISSUE THREAD

**Issue by Liu-Xin** [mpc-msri/EzPC#105]
Hello EzPC team,

I'm following the instructions in the SCI directory trying to compile the library. I am running ubuntu on a docker image.

I have the first two commands working,

> mkdir build && cd build
cmake .. [-DBUILD_TESTS=ON] [-DBUILD_NETWORKS=ON]

 but when running the make command after I get the following error.
<img width="985" alt="Screen Shot 2021-03-18 at 23 33 24" src="https://user-images.githubusercontent.com/24464082/111731889-6a71e400-8842-11eb-902c-22c187ffa63c.png">

I have libomp installed, so I am not sure why the error comes up.
<img width="756" alt="Screen Shot 2021-03-18 at 23 35 37" src="https://user-images.githubusercontent.com/24464082/111732017-af961600-8842-11eb-98b6-c0bf4ea70ae6.png">

I have all the required packages downloaded and in the correct version.
Any help would be welcomed. Thanks!

**Comment by bhatuzdaname** [comment]
Hi, I notice it is searching for a dylib which makes me think cmake is detecting your environment as MacOS instead of linux? Can you send me the output of `make VERBOSE=1` at the point the build fails. I want to see the full linking command.

**Comment by Liu-Xin** [comment]
<img width="985" alt="Screen Shot 2021-03-19 at 10 40 54" src="https://user-images.githubusercontent.com/24464082/111806064-98394600-889f-11eb-8b46-b6eee69df234.png">

Just some extra info if it helps, the host computer I am running docker on is Mac OS Big Sur

**Comment by bhatuzdanamemsr** [comment]
Can you do:
1. `mkdir /tmp/test_env; cd /tmp/test_env`
2. Create a CMakeLists.txt with the following content:
```
project(test)
message("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
```
3. `cmake`

Can you post the output here? I want to check if cmake is detecting the platform correctly. I am on a linux machine and get the following output:
..
CMAKE_SYSTEM_NAME: Linux
..

**Comment by Liu-Xin** [comment]
![Screen Shot 2021-03-22 at 09 46 16](https://user-images.githubusercontent.com/24464082/112008499-864fe100-8af3-11eb-9d3a-99e25ce037a9.png)

**Comment by Liu-Xin** [comment]
So the cmake command works and is detecting linux system, but its the make command that creates the error pasted in the first command.

**Comment by Liu-Xin** [comment]
Fixed the issue by deleting old directory and doing a fresh clone. May have to do with the first time I manually issued submodule update/clone command before doing cmake.
