### ISSUE TITLE
deployment error: The compilation of ocaml-base-compiler.4.10.0 failed at "make -j1 world"

### ISSUE THREAD

**Issue by xingpz2008** [mpc-msri/EzPC#112]
The compilation of ocaml-base-compiler.4.10.0 failed at "make -j1 world"
I am using CentOS 7. Is there any solution for this?
Thanks in advance!

**Comment by bhatuzdaname** [comment]
what is the error you get?
alternatively you could also try the docker image based on ubuntu 18.04 directly https://github.com/mpc-msri/EzPC#docker

**Comment by xingpz2008** [comment]
![643fe37e141a32ccd9624a8143fddfb](https://user-images.githubusercontent.com/47975406/132385238-f46f05f7-4b1a-4bdd-8e73-f04f56c134ae.png)

**Comment by xingpz2008** [comment]
This occurred when exec set_env_and_build.sh

**Comment by drunkenlegend** [comment]
Closing this issue as it seems to be no longer applicable. Please feel free to reopen if the issue persists or if you have any further concerns. Thank you!
