### ISSUE TITLE
Non-support for greaterEqual and RandomUniform

### ISSUE THREAD

**Issue by xingpz2008** [mpc-msri/EzPC#116]
Exiting compilation...
Currently we do not support the following ops: 
    RandomUniform
    GreaterEqual

**Comment by xingpz2008** [comment]
Binding_error(9285,19-9285,22): Cannot find variable: J30mv: cannot stat 'model_41_sci_OT0.cpp': No such file or directory

Error occurred as below when I tried to process my own .pb file when using CompileTFGraph.py

**Comment by drunkenlegend** [comment]
The above mentioned nodes are not supported for now, you can try using the new tool chain and try adding the node as given [here](https://github.com/mpc-msri/EzPC/tree/master/OnnxBridge#add-support-for-nodes) for your use case. Feel free to reopen issue incase of further queries.
