### ISSUE TITLE
Operation Support in ATHOS

### ISSUE THREAD

**Issue by xingpz2008** [mpc-msri/EzPC#125]
Hi,

Are the following operations supported in Athos?

Softmax, Sqrt, pow, Gather, Unsqueeze

Also, I have noticed that some operations are only supported in Athos-TF but not contained in Athos-ONNX?

Thanks!

**Comment by drunkenlegend** [comment]
[Here](https://github.com/mpc-msri/EzPC/tree/master/Athos#supported-nodes) is a list of nodes supported by Athos. Nodes commonly used in Networks are supported in Athos, it could be that some nodes are there in Athos-TF but not in Athos-Onnx.
Closing the issue. Please feel free to open the issue in case of further queries!
Thanks!
