### ISSUE TITLE
Undefined reference to main when trying to compile porthos

### ISSUE THREAD

**Issue by 0xlimE** [mpc-msri/EzPC#13]
Hello! I get this error when trying to compile porthos after the instructions.
![image](https://user-images.githubusercontent.com/58474540/74931908-ebad3c00-53e0-11ea-9fe4-9450c3be9973.png)

**Comment by 0xlimE** [comment]
It goes on with undefined references, I would love some assistance for fixing this :)

**Comment by mayank0403** [comment]
Hi,

Seems like you forgot to select one example neural net before compiling. Here is what you should do:
Go to: `EzPC/Porthos/src/example_neural_nets/network_config.h` and uncomment one of the neural network `#define`. For example, if you want to run ResNet50, then uncomment line #4 from ```
//#define F_RESNET50
```
to
```
#define F_RESNET50
```

**Comment by 0xlimE** [comment]
Thank you for your help!
