### ISSUE TITLE
[SCI] The output of communication rounds from tests does not match the paper

### ISSUE THREAD

**Issue by llCurious** [mpc-msri/EzPC#133]
Hey, i run the code in SCI/tests and notice that the number of rounds for the basic protocols does not match the paper. 

Below is the output from tests
![image](https://user-images.githubusercontent.com/21785695/172093549-1df18d9f-f7aa-48d2-8a26-dd890bf21eb1.png)

While in the paper, the wrap computation requires log l round, which should be 5  (log32 = 5).
The z_extend also should require logm + 2, which equals 7 (log32 +2 = 7), however, the output is 5.
![image](https://user-images.githubusercontent.com/21785695/172093741-e9e6cac8-83a1-4e78-814d-139500cf6b54.png)

**Comment by rahsharmar** [comment]
I think the rounds in the paper are computed analytically. The code will have additional rounds because of implementation artifacts.
