### ISSUE TITLE
Running Porthos (with resnet after tutorial) gives segfault

### ISSUE THREAD

**Issue by 0xlimE** [mpc-msri/EzPC#14]
Hi, I am hoping to be able to run resnet but i get  a segfault. I set up the make file to use -g as a flag and run the party0.sh with gdb. I get the following error.
![image](https://user-images.githubusercontent.com/58474540/74938251-ef938b00-53ed-11ea-979f-e60eee8e78df.png)

I have made the resnet after the specification in Athos. 

I would be very happy to get some help to resolve this :-)

**Comment by nishkum** [comment]
We fixed a very related issue recently. Can you do a pull and recheck?

**Comment by nishkum** [comment]
Please reopen this issue if the problem still persists.
