### ISSUE TITLE
error when compiling SCI on Ubuntu18.04

### ISSUE THREAD

**Issue by Samuel-1029** [mpc-msri/EzPC#145]
there is some error when I call "cmake -DCMAKE_INSTALL_PREFIX=./install .. -DBUILD_TESTS=ON -DBUILD_NETWORKS=ON" .

CMake Error: The source directory "/home/toor/EzPC/SCI/build/[-DNO_REVEAL_OUTPUT=ON]" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

Could you please tell me how to solve it?

**Comment by drunkenlegend** [comment]
The command "cmake -DCMAKE_INSTALL_PREFIX=./install .. -DBUILD_TESTS=ON -DBUILD_NETWORKS=ON"  works fine on Ubuntu18.04. Your error suggests you earlier tried using a different command, try to remove and make a fresh build directory where you execute the commands.
For more information please see [SCI](https://github.com/mpc-msri/EzPC/tree/master/SCI#compilation).
