### ISSUE TITLE
Running Docker for EzPC ends at step 32/38

### ISSUE THREAD

**Issue by ccurelea** [mpc-msri/EzPC#15]
Hello,

I am trying to install and run EzPC with the docker method on Ubuntu. When I run sudo docker build -t ezpc_image . it works well but then ends at step 32/38. 

in red it states 

EzPC/EzPC/ABY_example/*': No such file or directory (second last line in image)

See the attached image. Thank you so much for any help you can provide!
![Screen Shot 2020-02-20 at 9 04 00 AM](https://user-images.githubusercontent.com/47864152/74941034-6023b300-53c0-11ea-938a-2e466325542a.png)

**Comment by mayank0403** [comment]
Hi,

The Dockerfile in our Master branch is outdated. I am working in another branch (random_forest) where Dockerfile is latest and runs correctly. I would suggest that you do `git checkout random_forest`, try to build the docker image from that branch. Once the docker image is built, you can run the docker container and inside the container you can do `git checkout master && git pull`. This way, you will have master branch code inside your docker container.

Here are the instructions step by step:
```
git clone https://github.com/mpc-msri/EzPC
cd EzPC/EzPC/Docker
git checkout random_forest
sudo docker build -t ezpc_image .
sudo docker run --network host --privileged -it ezpc_image
cd Docker && git checkout master && git pull
```

**Comment by mayank0403** [comment]
The last command above `cd Docker && git checkout master && git pull` should be run inside the docker container.

**Comment by ccurelea** [comment]
So for the final line should I use 

docker-compose run <container name> cd Docker && git checkout master && git pull

**Comment by ccurelea** [comment]
Correction ****

docker-compose run <container name> cd Docker && git checkout master && git pull

**Comment by mayank0403** [comment]
No. When you run the second-last command `sudo docker run --network host --privileged -it ezpc_image`, your terminal will automatically enter bash inside the docker container. So, you don't need anything special. Just after running `sudo docker run --network host --privileged -it ezpc_image` command, you will enter the bash of docker, now you can run the last command there.

**Comment by ccurelea** [comment]
First off thank you for your support so far it means a lot! I have been stuck on this for a while and your help is very appreciated!

All works well. I am on the last step and when I run ./run_docker_example_server.sh I get a no such file or directory error. 

See attached image.
![Screen Shot 2020-02-20 at 12 51 46 PM](https://user-images.githubusercontent.com/47864152/74963645-15199800-53e0-11ea-8085-3f3b8066c523.png)

**Comment by mayank0403** [comment]
Can you tell me what exactly do you want to run? I mean, which example. I can help you better if you let me know about this.

I mean, you might have to make changes to some scripts here and there to run EzPC examples. Knowing what examples you are interested me, can help me in directing you towards the right path.

**Comment by ccurelea** [comment]
Currently I am trying to complete the EzPC setup from the readme.md file. I am following the docker installation. I am trying to execute the example.

I am at this step 
- Now that you have 2 sessions open, you can run client on one session and server on the other.
- Enter Docker directory in both the sessions and run `./run_docker_example_server.sh` in one and `./run_docker_example_client.sh` in the other.

when I run the ./run_docker_example_server.sh in the session I am returned with No such file or directory. As seen in the image. 
![Screen Shot 2020-02-20 at 12 51 46 PM](https://user-images.githubusercontent.com/47864152/74965824-e1407180-53e3-11ea-9bca-bba0ba734a08.png)

Do you have any suggestions?

Thank you so much

**Comment by mayank0403** [comment]
I have pushed some changes. Things should work now. 

Do the same as I described earlier. Follow these steps now (from the start):
```
git clone https://github.com/mpc-msri/EzPC
cd EzPC/EzPC/Docker
git checkout random_forest
sudo docker build -t ezpc_image .
sudo docker run --network host --privileged -it ezpc_image
cd Docker && git checkout master && git pull
./compile_docker_example.sh 0
```
Now on one docker terminal session, run:
```
run_docker_example_client.sh
```
On the other one, run:
```
run_docker_example_server.sh
```

**Comment by mayank0403** [comment]
When the client and server start executing, they might want inputs from the user. You should provide input if required. You will know if the input is required if after running client and server scripts (`run_docker_example_server.sh` and `run_docker_example_client.sh`), one or both of them wait at a certain step. If they wait, you provide input then.

**Comment by ccurelea** [comment]
I am almost done runnning the EzPC example this is what I have done so far

**1. First Terminal** 
git clone https://github.com/mpc-msri/EzPC
cd EzPC/EzPC/Docker
git checkout random_forest
sudo docker build -t ezpc_image .
sudo docker run --network host --privileged -it ezpc_image
cd Docker && git checkout master && git pull
chmod u+r+x compile_docker_example.sh
./compile_docker_example.sh 0
chmod u+r+x run_docker_example_client.sh
/run_docker_example_client.sh

![Screen Shot 2020-02-20 at 4 07 32 PM](https://user-images.githubusercontent.com/47864152/74978685-2ae88680-53fb-11ea-9c53-ba58410b21c0.png)

**2. Second Terminal** 
sudo docker container ls
sudo docker exec -it CONTAINER_ID /bin/bash
cd Docker && git checkout master && git pull
chmod u+r+x run_docker_example_server.sh
./run_docker_example_server.sh

![Screen Shot 2020-02-20 at 4 18 47 PM](https://user-images.githubusercontent.com/47864152/74979471-b1519800-53fc-11ea-941b-73d707ed8e5e.png)

**The Issue**
 In both cases after I run 
./run_docker_example_server.sh
and /run_docker_example_client.sh

I get this 

/ezpc-workdir/ABY-latest/ABY/build/bin/server
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./run_docker_example_server.sh: line 30:   437 Aborted                 (core dumped) ./docker_binop_example -r 1

**Comment by mayank0403** [comment]
https://github.com/mpc-msri/EzPC/issues/9 should help you with std::bad_alloc error.

**Comment by mayank0403** [comment]
Run this from the `Docker/` directory:
```
vim ../../../../ABY-latest/ABY/src/examples/docker-test/common/millionaire_prob.cpp
```
In this file, you will find the line `party = new ABYParty(role, address, port, seclvl, bitlen, nthreads, mt_alg, 520000000);`. Once you find this line, follow the instructions as pointed out in #9

**Comment by nishkum** [comment]
Please reopen if the issue persists.
