### ISSUE TITLE
SCI failed to test binaries.

### ISSUE THREAD

**Issue by ignorantz** [mpc-msri/EzPC#166]
The following problem occurs when testing executable files in the bin folder:

Program received signal SIGILL, Illegal instruction.

__static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/lib/gcc/x86_64-linux-gnu/9/include/emmintrin.h:592

592	  return __extension__ (__m128i)(__v2di){ __q0, __q1 };

**Comment by ignorantz** [comment]
> Can you share the machine you are running it on and the commands you used ?
The machine I used was HP ProBook 450 G8 Notebook PC with Intel i7-1165G7 CPU. All tests of executable files were failed. (Program received signal SIGILL, Illegal instruction.)
But now I'm using a desktop computer, the tests are successful.

**Comment by drunkenlegend** [comment]
Great! Closing this issue.
