### ISSUE TITLE
SCI resnet50-OT

### ISSUE THREAD

**Issue by MEAMITBHOWMICK** [mpc-msri/EzPC#168]
I was trying to compile the resnet50-OT but it is not working, the program starts but the execution is not ending any output is coming.

I also have another query that where is the inputs and model weights for resnet50

**Comment by MEAMITBHOWMICK** [comment]
I compiled the SCI with the command mentioned here https://github.com/mpc-msri/EzPC/tree/master/SCI#compilation

After that many binaries are created in build/bin
now I want to run resnet50-OT but it's not working.

I tried with the command ./resnet50-OT r=1 and ./resnet50-OT r=2

I have not found any input or any model file corresponding it, can you tell  me how to make it working.

**Comment by MEAMITBHOWMICK** [comment]
I have download the model from [here](https://github.com/onnx/models/tree/main/vision/classification/resnet)
I tried with this code (cat ../../resnet50-v1-7/resnet50-v1-7.onnx | ./resnet50-OT r=1) and (cat ../../resnet50-v1-7/test_data_set_0/input_0.pb | ./resnet50-OT r=2) after that I got this output on client end[https://drive.google.com/file/d/1tolSekSWIVPa0hdGXP4SVyXPih4AHIha/view?usp=sharing](url) on server end[https://drive.google.com/file/d/1tAgWg7CjvZ8oqLGcGWvFSzQwnOTZ2-dO/view?usp=sharing](url), I am unable to figureout what the output indicates. can you please explain.

also can I run any onxx model?if yes, how to do that

**Comment by drunkenlegend** [comment]
- The model you are using works fine with EzPC/Athos, however the binary you used to run the model is there for testing purpose and getting benchmarks, the binary has a ArgMax at the end because of which a single value is printed, and the value is scaled up based on the scale and bitlength provided in binary.
- Again giving a link for the demo following which you will be able to successfully compile the model and execute. [link](https://github.com/mpc-msri/EzPC/tree/master/Athos/demos/onnx) .
     -  You will have to modify the config.json file for your model name and input shape.
     - Your model also has a variable batch size which is not allowed, you can keep a fixed batch size of 1 using [onnxruntime](https://onnxruntime.ai/docs/tutorials/mobile/helpers/make-dynamic-shape-fixed.html#making-a-symbolic-dimension-fixed) and then try to run the demo with your model.
     - You should get a output of size [1,1000] at the end of inference, following the steps in demo you will be able to get the output as a numpy array.

**Comment by drunkenlegend** [comment]
Marking this as resolved, feel free to reopen if issue persists!
