### ISSUE TITLE
How to convert a downloaded cifar dataset into the form requested by the input？

### ISSUE THREAD

**Issue by HuifengShrimp** [mpc-msri/EzPC#169]
I am trying to run minionn-cnn on cifar-10 dataset in "EzPC/FSS/benchmarks/minionn-cnn.cpp". I have already downloaded the cifar-10 dataset using "SetupCIFAR10.sh" in "EzPC/Athos/HelperScripts". But I got no idea on how to covert such binary datasets into the needed form. How can I run minionn-cnn with cifar-10 using the FSS component?

**Comment by drunkenlegend** [comment]
You can use this [link](https://github.com/mpc-msri/EzPC/tree/master/Athos/Networks/SqueezeNetCIFAR10) to see how cifar-10 dataset is modified as required by model. You can use the same `Utils.py` file with some modifications as required by your model.
To run minionn-cnn with FSS component, try following this [example](https://github.com/mpc-msri/EzPC/blob/master/sytorch/Toy%20example-%20single%20inference.md) which uses FSS as a backend.

**Comment by drunkenlegend** [comment]
You can also simply use [OnnxBridge](https://github.com/mpc-msri/EzPC/tree/master/OnnxBridge#llama) to run the onnx model you have.
Closing this issue! Feel free to reopen if you have any other queries.
