### ISSUE TITLE
How to get network's accuracy?

### ISSUE THREAD

**Issue by ZJG0** [mpc-msri/EzPC#172]
I want to test the network's accuracy implemented by EzPC. There are two methods, one is training a model by EzPC and inferencing the accuracy, the other is converting the trained plaintext model to an EzPC model and inferencing. So, which should I choose and how do it? Please give me some advice.

**Comment by rahsharmar** [comment]
Choose the latter. Scripts here should be useful.
https://github.com/mpc-msri/EzPC/tree/master/Athos#preprocessing-images-and-running-inference-on-imagenet-validation-dataset
