### ISSUE TITLE
question about SIGMA: Secure GPT Inference with Function Secret Sharing

### ISSUE THREAD

**Issue by TheSunWillRise** [mpc-msri/EzPC#197]
Hello there, thanks for your great work in FSS.
I want to know how to reproduce the results in your paper "SIGMA: Secure GPT Inference with Function Secret Sharing".
Does FSS-GPU work now?

**Comment by rahsharmar** [comment]
https://github.com/mpc-msri/EzPC/tree/master/GPU-MPC has code for both Orca and Sigma.

**Comment by neha-jawalkar** [comment]
The GPU-MPC/experiments/sigma folder has a readme as well.
