### ISSUE TITLE
Synchronization issue?

### ISSUE THREAD

**Issue by rahsharmar** [mpc-msri/EzPC#2]
The behavior of output changes according to whether I provide server inputs first or client inputs first. Sometimes the outputs are shown only to client with ALL if server inputs are provided first.

**Comment by nishkum** [comment]
Can you please post an ezpc code snippet which reproduces this?

**Comment by rahsharmar** [comment]
The docker example

**Comment by nishkum** [comment]
Closing this as the problem was with the script to run the example.
