### ISSUE TITLE
Code for SIGMA paper

### ISSUE THREAD

**Issue by jimouris** [mpc-msri/EzPC#209]
The README mentions the SIGMA paper but I cannot find the code for it or any instructions. Is it pushed to this repository?

**Comment by rahsharmar** [comment]
https://github.com/mpc-msri/EzPC/tree/master/GPU-MPC has code for both Orca and Sigma.

**Comment by neha-jawalkar** [comment]
The GPU-MPC/experiments/sigma folder has a readme as well.
