### ISSUE TITLE
A question about the usage of DCF implementation

### ISSUE THREAD

**Issue by Xenooooooooo** [mpc-msri/EzPC#211]
Hi, I was using the dcf implementation in EzPC. I've managed to run the dcf code in the newest libOTe repository, but I just cannot understand the content of the output and how can I use the output. Where can I find the explatation, example or uasge of the DCF code?

Btw, my scheme is below. 

I've set:
````
int32_t bitlength = 64;
PRNG prng(sysRandomSeed());
PRNG prngShared(sysRandomSeed());

int bit_in = 20;            // DCF's input bit-length?
int bit_out = 30;         // DCF's output bit-length?
uint64_t alpha = 30;  // DCF's alpha, the splitting point?
uint64_t beta = 10;    // one of the DCF's output value, 0 or beta (?
GroupElement alpha_dcf(alpha);
GroupElement beta_dcf(beta);
        
GroupElement input_element(15); // use as the input of DCF?
````

And in the testing funtion is:
````
std::pair<DCFKeyPack, DCFKeyPack> key = keyGenDCF(bit_in, bit_out, alpha_dcf, beta_dcf);

evalDCF(1, &result_1, input_element, key.first);
evalDCF(2, &result_2, input_element, key.second);

std::cout << "\nkey.first.Bin : " << key.first.Bin << std::endl;
std::cout << "key.first.Bout : " << key.first.Bout << std::endl;
std::cout << "key.first.g : " << key.first.g->value << std::endl;
std::cout << "key.first.groupsize : " << key.first.groupSize << std::endl;
std::cout << "key.first.k : " << key.first.k << std::endl;
std::cout << "key.first.v : " << key.first.v->value << std::endl;

std::cout << "result_0.value : " << std::bitset<64>(result_1.value) << std::endl;
std::cout << "result_1.value : " << std::bitset<64>(result_2.value) << std::endl;
std::cout << "result_xor : " << std::bitset<64>(result_1.value ^ result_2.value) << std::endl;
std::cout << "result_add : " << std::bitset<64>(result_1.value + result_2.value) << std::endl;
std::cout << "result_minus : " << std::bitset<64>(result_1.value - result_2.value) << std::endl;
std::cout << "result_and : " << std::bitset<64>(result_1.value & result_2.value) << std::endl;

freeDCFKeyPackPair(key);
````

Since two PRNGs are keyed with randomseed, the output of `key.first.g->value, key.first.k, key.first.v->value` are changing, and I think it's the same with the key.second. And 'result_0.value, result_1.value' are changing, too.

The question is, `result_xor, result_add, result_minus` are changing. In the definition of DCF, $F_1(x)$ add / minus $F_2(x)$ should equal to $\beta$ or 0, but **none** of the value above is. 

So what is the correct way of using this implementation, and how to read the result? I'm a bit confused. Thanks!

PS: one of the output is:
````
key.first.Bin : 20
key.first.Bout : 30
key.first.g->value : 389239728
key.first.groupsize : 1
key.first.k : 0x1c11bd0
key.first.v->value : 943733590
result_0.value : 0001100011101111000010000101001100011111001101100010000111111110
result_1.value : 0001011010100011111111001110110011100000110010011101110111111000
result_xor :     0000111001001100111101001011111111111111111111111111110000000110
result_add :     0010111110010011000001010011111111111111111111111111111111110110
result_minus :   0000001001001011000010110110011000111110011011000100010000000110
result_and :     0001000010100011000010000100000000000000000000000000000111111000
````

**Comment by Xenooooooooo** [comment]
Oh, I forget to give the information that, due to the old version of `cryptoTools` in EzPC/FSS, function `ecbEncTwoBlocks()` and `ecbEncFouorBlocks()` are no longer exist in the newest version of `cryptoTools`. 

Instead, I use `ecbEncBlocks()` with parameter 2 and 4 in the middle to replace the old function.

**Comment by kanav99** [comment]
@Xenooooooooo can you make these two changes and try:

1. When you call `evalDCF` use 0 and 1 as party identifiers, not 1 and 2

```
evalDCF(0, &result_1, input_element, key.first);
evalDCF(1, &result_2, input_element, key.second);
```

2. Before printing result_add, can you do a `% 2^30`?

```
std::cout << "result_add : " << std::bitset<64>((result_1.value + result_2.value) % (1<<bit_out)) << std::endl;
```

Let me know if it works. If it still doesn't work, can you send me the entire test file and I can try to find the issue

**Comment by Xenooooooooo** [comment]
Okay, the output is correct now, thanks a lot for your response!
