### ISSUE TITLE
AttributeError: 'Int' object has no attribute 'idf' while executing CompileTF.sh

### ISSUE THREAD

**Issue by Vito-Swift** [mpc-msri/EzPC#61]
I have fetched the source and installed the docker as instruction. After ensuring that ABY and EzPC compiler have been built in the docker, I tried to follow README in [https://github.com/mpc-msri/EzPC/tree/master/Athos](https://github.com/mpc-msri/EzPC/tree/master/Athos) to see how the program works. The first several steps are quite smooth, until I tried to compile the model into Porthos by executing the script `./CompileTF.sh -b 64 -s 12 -t PORTHOS -f ./Networks/ResNet/ResNet_main.py`, I got following error log:

```
......[many lines of error trace back]......
File "/ezpc-workdir/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 121, in visit
    return self.visitLet(node, args)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/IR/IRBuilderCSF.py", line 863, in visitLet
    (prog_2, expr_2) = self.visit(node.expr)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 121, in visit
    return self.visitLet(node, args)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/IR/IRBuilderCSF.py", line 863, in visitLet
    (prog_2, expr_2) = self.visit(node.expr)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 121, in visit
    return self.visitLet(node, args)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/IR/IRBuilderCSF.py", line 863, in visitLet
    (prog_2, expr_2) = self.visit(node.expr)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 121, in visit
    return self.visitLet(node, args)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/IR/IRBuilderCSF.py", line 863, in visitLet
    (prog_2, expr_2) = self.visit(node.expr)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/AST/ASTVisitor.py", line 121, in visit
    return self.visitLet(node, args)
  File "/ezpc-workdir/EzPC/Athos/SeeDot/IR/IRBuilderCSF.py", line 862, in visitLet
    self.name_mapping[idf] = expr_1.idf
AttributeError: 'Int' object has no attribute 'idf'
[WARNING] Running as root is not recommended
Traceback (most recent call last):
  File "./HelperScripts/AthosToPorthosTemp.py", line 31, in <module>
    with open(filename, 'r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: '/ezpc-workdir/EzPC/Athos/Networks/ResNet/ResNet_main_64_porthos0.cpp'
```

I guess the error might raise due to an incorrect software version or incorrect input. Can anyone provide some suggestions on how can I proceed to next step? Thanks

**Comment by nishkum** [comment]
Hi, we have not tested the docker version for Athos. It has only been tested for support for EzPC and ABY. The docker version uses a specific commit of some branch of this repo to clone and that could be causing the issue. 
Can you try one of these 2 things: 
- setup Athos outside docker (following the instructions to setup the right version of TF, python and dependent libraries) from README.md.
- or in the docker itself, do a git checkout master ; git pull ; install dependent libraries specified for Athos and retry.

**Comment by Vito-Swift** [comment]
> Hi, we have not tested the docker version for Athos. It has only been tested for support for EzPC and ABY. The docker version uses a specific commit of some branch of this repo to clone and that could be causing the issue.
> Can you try one of these 2 things:
> 
> * setup Athos outside docker (following the instructions to setup the right version of TF, python and dependent libraries) from README.md.
> * or in the docker itself, do a git checkout master ; git pull ; install dependent libraries specified for Athos and retry.

Thanks for replying, I will have a try and update this issue timely. FYI, the dependencies installed in my docker is the same as in the README.

**Comment by nishkum** [comment]
Please reopen if you still continue facing the issue.

**Comment by Vito-Swift** [comment]
Hi, I have just tested the two methods you provide, but the error log seems the same. Can you try to run the README you provide on a new machine in case there is a dependency issue or missed step?

My machine is Ubuntu 18.04 on Linux 4.15.0, python version 3.6, tensorflow version 1.11, cmake version 3.14.2, opam version 1.2.2

**Comment by nishkum** [comment]
Hi, Thanks for pointing the issue. Indeed I could reproduce the error and it turned out it was a regression from the last major checking we did. I checked in the the fix in master - you can pull and everything should just work (I double checked that indeed everything is working).
I will close this issue for now - please reopen if you continue facing issues. 
Thanks!
