### ISSUE TITLE
Fatal error: exception Failure("Modulo and {bitlen not equal to 32/64} only supported for CPPRING/PORTHOS2PC backend.")

### ISSUE THREAD

**Issue by rasswanth-s** [mpc-msri/EzPC#70]
I tried setting modulo and bit length but still the error persists.
I have attached the screenshot.
![Screenshot from 2021-01-10 16-54-44](https://user-images.githubusercontent.com/43314053/104121523-e3e1e780-5364-11eb-9b59-d03d40ea04cc.png)

**Comment by bhatuzdaname** [comment]
In your screenshot, I cannot see that you have set the bitlength. Can you try this:
./ezpc.sh --bitlen 32 test_suite/dot_product.ezpc
It works for me.

**Comment by rasswanth-s** [comment]
@bhatuzdaname Yeah It resolved, I must have tried the repo.Thank you.
