### ISSUE TITLE
[bias_add] Support for "NC.." input

### ISSUE THREAD

**Issue by bhatuzdaname** [mpc-msri/EzPC#72]
Add support for "NC.." data format for [bias_add](https://www.tensorflow.org/api_docs/python/tf/nn/bias_add) node.

For ```tf.nn.bias_add(value, bias)```

bias is a 1-D vector with shape equal to that of channel dimension.

We currently support broadcasting when value is "N..C". This falls in the normal broadcasting rules of numpy, ([1,250,250,3] + [3])

However when value is "NC..", then normal broadcasting doesn't work. eg: [1,3,250,250] + [3].

**Failing test case: ```test_bias_add```**

**Comment by drunkenlegend** [comment]
Issue is no longer applicable as this is handled by [Optimize](https://github.com/mpc-msri/EzPC/blob/3db904053f5c6396da8a6b3aff6a1b340220241f/OnnxBridge/utils/optimizations.py#L236) function in OnnxBridge. Further Add node is supported in new backends.
