### ISSUE TITLE
References?

### ISSUE THREAD

**Issue by YaLunDong** [mpc-msri/EzPC#8]
Thanks for your great work! I wonder if there are any references for coding except your paper in EuroS&P2019, which contains not enough coding examples. Thank you.

**Comment by mayank0403** [comment]
You can take a look at wiki section. It provides coding examples.

**Comment by YaLunDong** [comment]
> In case you are talking about EzPC and not crypTFlow.
> You can take a look at wiki section. It provides coding examples for EzPC.
Thank you for your kindness
