### ISSUE TITLE
std::bad_alloc while executing ezpc with ABY Backend

### ISSUE THREAD

**Issue by rasswanth-s** [mpc-msri/EzPC#9]
![rsz_screenshot_from_2020-02-17_15-36-28](https://user-images.githubusercontent.com/43314053/74644377-325e2480-519c-11ea-86d1-600d004d389a.png)

I ran it after loading dot_product0.cpp into the build directory

**Comment by nishkum** [comment]
Hi Rasswanth,
You might be running out on memory. ABY by default allocates a large memory which is not needed. Can you search for the following line in the ABY program you are running:

party = new ABYParty(role, address, port, seclvl, bitlen, nthreads, mt_alg, 520000000);

The last parameter is the number of gates and controls how much memory to allocate. Try reducing that parameter - say from 520000000 to 5200000 or something - that should make it work.

**Comment by rasswanth-s** [comment]
It is resolved.Thank you
