### ISSUE TITLE
[SCI][square] Assertion on multiplying secret with secret

### ISSUE THREAD

**Issue by bhatuzdaname** [mpc-msri/EzPC#93]
ElemWiseSecretSharedVectorMult is not implemented. Add support for it.

Reproduce error: ```pytest -rs . -k "test_uop[square-float32-a_shape0]" --backend="2PC_OT"```

**Comment by drunkenlegend** [comment]
Hi @bhatuzdaname, is this still an open issue?

**Comment by drunkenlegend** [comment]
It has been implemented now.
